# Generated by Django 3.0.4 on 2020-11-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_details',
            name='dob',
        ),
    ]
