# Generated by Django 3.0.4 on 2020-11-25 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pat', '0002_remove_p_details_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_details',
            name='img',
        ),
    ]
