# Generated by Django 3.0.4 on 2020-11-30 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField(choices=[(1, 'Started'), (2, 'Ended'), (3, 'Cancelled')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_to_hospital', to='hospital.H_Details')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_from_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
